name: build And Deploy VUE2-APP To Dev Env
on:
  push:
    branchs:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     # 下载源码
    - name: Checkout
      uses: actions/checkout@master
    # 打包构建
    - name: Build
      uses: actions/setup-node@master
    - run: npm install
    - run: npm run build
    - run: tar -zcvf release.tgz qiankun-vue2-subapp
    # 部署到服务器
    - name: Deploy
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        scp: |
          './release.tgz' => /usr/local/nginx/qiankun_apps/sub_apps
        last_ssh: |
          cd /usr/local/nginx/qiankun_apps/sub_apps
          tar zxvf release.tgz
        